# Generated by Django 4.1.4 on 2022-12-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newuser",
            options={"verbose_name_plural": "Users"},
        ),
    ]
