# Generated by Django 4.1.4 on 2022-12-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0005_alter_imagemodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="user",
            field=models.CharField(max_length=50),
        ),
    ]
